BabelFishProtocol/babelfish-dapp

src/theme/components.ts
=> add custom scrollbar styles

src/components/DataTable/DataTable.component.tsx, src/components/DataTable/DataTable.mock.ts, src/components/DataTable/DataTable.test.tsx, src/components/DataTable/DataTable.types.ts, src/pages/Dashboard/TransactionsTable/TransactionsTable.component.tsx, src/pages/Dashboard/TransactionsTable/TransactionsTable.container.tsx, src/pages/Dashboard/TransactionsTable/TransactionsTable.types.ts, src/pages/ProposalDetails/VotesBlock/VotesBlock.votesList.tsx, src/pages/ProposalsList/ProposalsList.component.tsx, src/pages/Staking/StakesList/StakesList.component.tsx, src/pages/Staking/StakingHistory/StakingHistory.component.tsx, src/pages/Staking/StakingHistory/StakingHistory.container.tsx, src/pages/Staking/StakingHistory/StakingHistory.types.ts, src/pages/Staking/VestsList/VestsList.component.tsx
=> add error state to data table

src/hooks/useActiveWeb3React.test.tsx, src/hooks/useActiveWeb3React.ts
My mistake while creating the logic of setting the modal. 
This thread explains my bug
https://stackoverflow.com/questions/62336340/cannot-update-a-component-while-rendering-a-different-component-warning
=> fix walletNotConnectedModal error

src/pages/Staking/StakesList/IncreaseStake/IncreaseStake.component.tsx, src/pages/Staking/StakesList/IncreaseStake/IncreaseStake.container.tsx, src/pages/Staking/StakesList/IncreaseStake/IncreaseStake.types.ts, src/store/staking/sagas/addNewStake.test.ts, src/store/staking/sagas/addNewStake.ts, src/store/staking/sagas/increaseStake.test.ts, src/store/staking/sagas/increaseStake.ts, src/store/staking/staking.mock.ts, src/store/staking/staking.sagas.ts, src/store/staking/staking.selectors.ts, src/store/staking/staking.slice.ts, src/store/staking/staking.state.ts, src/store/staking/staking.utils.ts, src/store/utils/utils.reducers.test.ts, src/store/utils/utils.reducers.ts, src/store/utils/utils.types.ts
- move increase stake form call to saga
- add stepper
=> increase stake form improvements

src/components/InputPillGroup/ButtonPillGroup/ButtonPillGroup.types.ts, src/components/InputPillGroup/InputWithButtonPillGroup.component.tsx, src/components/InputPillGroup/InputWithButtonPillGroup.controlled.tsx, src/components/InputPillGroup/InputWithButtonPillGroup.types.ts, src/constants.ts, src/pages/Aggregator/AggregatorInfo/AggregatorInfo.component.tsx, src/pages/Aggregator/SendAmount/SendAmount.component.tsx, src/pages/Aggregator/SendAmount/SendAmount.container.tsx, src/pages/Aggregator/SendAmount/SendAmount.types.tsx
Aggregator improvements/fixes
* Fix decimals in the sendAmount input
* Check whether minTransfer <= sendAmount <= available balance/maxTransfer
* Remove undefined as tokenName in AggregatorInfo
* Improve typings
=> Aggregator improvements/fixes

src/App.tsx, src/constants.ts, src/pages/Claim/Claim.component.tsx, src/pages/Claim/Claim.container.tsx, src/pages/Claim/Claim.fields.ts, src/pages/Claim/Claim.types.ts
=> Claim Fish Balance - UI

src/pages/Aggregator/Aggregator.hooks.test.tsx
=> Added tests for aggregator hooks

src/components/DataTable/DataTable.component.tsx, src/components/DataTable/DataTable.test.tsx, src/pages/Staking/StakesList/StakesList.component.tsx, src/pages/Staking/StakingHistory/StakingHistory.component.tsx, src/pages/Staking/VestsList/VestsList.component.tsx, src/theme/components.ts, src/theme/palette.ts
=> feature/ Color change every other row in the table, set similar height for tables

src/pages/ProposalDetails/ProposalDetails.component.tsx
=> feature / add word 'estimate' to the time when proposal is ending

docker-compose.yaml, package.json, start.sh
Just run `yarn deploy` to update, build and deploy app
=> Add deploy command

src/App.tsx, src/components/ErrorAlert/ErrorAlert.component.tsx, src/components/Wallet/WalletDropdown/WalletDropdown.tsx, src/config/wallets.ts, src/pages/Aggregator/AggregatorInfo/AggregatorInfo.component.tsx, src/store/app/app.mock.ts, src/store/app/app.selectors.test.ts, src/store/app/app.selectors.ts, src/store/app/app.slice.ts, src/store/app/app.state.ts, src/theme/components.ts
=> error alert component

src/pages/Aggregator/Aggregator.component.tsx, src/pages/Aggregator/Aggregator.container.tsx, src/pages/Aggregator/Aggregator.types.ts
Resolves https://sovryn.atlassian.net/browse/SOV-695
=> Set fixed XUSD conversion ratio

src/config/bridges.ts, src/config/chains.ts, src/config/pools.ts, src/config/tokens.ts, src/pages/Aggregator/Aggregator.hooks.test.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-987
=> Remove BSC Testnet

src/config/bridges.ts, src/config/chains.ts, src/config/contracts.ts, src/config/pools.ts, src/config/tokens.ts, src/store/aggregator/aggregator.selectors.ts, src/store/aggregator/sagas/depositTokens.test.ts, src/store/aggregator/sagas/depositTokens.ts, src/store/aggregator/sagas/withdrawTokens.test.ts, src/store/aggregator/sagas/withdrawTokens.ts, src/store/app/app.selectors.ts
Resolves https://sovryn.atlassian.net/browse/SOV-923
=> Add Sepolia network and SEPUSD support

src/constants.ts, src/pages/AddProposal/AddProposal.component.tsx, src/pages/ProposalDetails/ProposalDetails.container.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-1176
=> SOV-1176: Remove governor owner from create proposal modal

src/components/Dropdown/Dropdown.component.tsx, src/components/Dropdown/Dropdown.controlled.tsx, src/config/contracts.ts, src/constants.ts, src/contracts/abi/PauseManager.json, src/pages/Aggregator/Aggregator.component.tsx, src/pages/Aggregator/Aggregator.container.tsx, src/pages/Aggregator/Aggregator.types.ts, src/store/aggregator/aggregator.sagas.ts, src/store/aggregator/aggregator.selectors.ts, src/store/aggregator/aggregator.slice.ts, src/store/aggregator/aggregator.state.ts, src/store/app/app.selectors.ts, src/store/dashboard/sagas/fetchDashboardBalances.test.ts, src/store/proposals/sagas/addProposal.test.ts, src/store/proposals/sagas/castVote.test.ts, src/store/proposals/sagas/proposalDetails.test.ts, src/store/proposals/sagas/proposalDetailsCalls.test.ts, src/store/proposals/sagas/proposalList.test.ts, src/store/vesting/sagas/delegateVest.test.ts, src/store/vesting/sagas/withdrawVest.test.ts, src/store/vesting/vesting.utils.test.ts
Resolves https://sovryn.atlassian.net/browse/SOV-1175
=> SOV 1175: Deposit pause functionality

src/pages/Aggregator/Aggregator.hooks.ts
Resolves https://sovryn.atlassian.net/browse/SOV-1411
=> SOV-1411: Enforce bAsset <> XUSD selection

src/constants.ts, src/pages/Aggregator/SendAmount/SendAmount.container.tsx, src/store/aggregator/aggregator.sagas.ts, src/store/aggregator/aggregator.selectors.ts, src/store/aggregator/aggregator.slice.ts, src/store/aggregator/aggregator.state.ts
Resolves https://sovryn.atlassian.net/browse/SOV-1455
=> SOV-1455: Validate destination token aggregator balance

src/pages/Aggregator/Aggregator.hooks.ts
Resolves https://sovryn.atlassian.net/browse/SOV-1453
=> SOV-1453: Fix destination token options

src/App.tsx, src/components/Logo/Logo.component.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-1654
=> SOV-1654: Hide Dashboard page

src/pages/Aggregator/SendAmount/SendAmount.container.tsx, src/store/aggregator/aggregator.sagas.ts, src/store/aggregator/aggregator.selectors.ts
Resolves https://sovryn.atlassian.net/browse/SOV-1658
=> SOV-1658: Fetch aggregator balances for bridge assets

src/pages/Staking/StakesList/StakesList.actions.tsx, src/pages/Staking/Staking.component.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-1659
=> SOV-1659: Disable stake buttons

src/pages/Aggregator/Aggregator.component.tsx, src/pages/Aggregator/AggregatorInfo/AggregatorInfo.component.tsx, src/pages/Aggregator/AggregatorInfo/AggregatorInfo.container.tsx, src/pages/Aggregator/AggregatorInfo/AggregatorInfo.types.ts
Resolves:
- https://sovryn.atlassian.net/browse/SOV-1687
- https://sovryn.atlassian.net/browse/SOV-1686
=> SOV-1687: Add aggregator balance to XUSD -> bAsset transfers

src/config/pools.ts, src/pages/Staking/Staking.hooks.ts
=> Mainnet release

src/pages/Staking/Staking.component.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-2235
=> SOV-2235: Remove staking maintenance mode

src/components/DateSelector/DateSelector.utils.ts, src/constants.ts
Resolves https://sovryn.atlassian.net/browse/SOV-2245
=> SOV-2245: Fix staking duration

README.md, src/App.tsx, src/components/Footer/Footer.component.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-2196
=> SOV-2196: Add a link to the latest GH release

src/pages/Aggregator/Aggregator.component.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-2079
=> SOV-2079: Fix tokens selection

src/config/sovryn-onboard-chains.ts, src/contracts/abi/Staking.json, src/pages/Staking/Staking.component.tsx, src/pages/Staking/Staking.hooks.ts, src/store/app/app.selectors.ts
Resolves https://sovryn.atlassian.net/browse/SOV-2482
=> SOV-2482: Automatic staking maintenance
